export type JobCategory = 'railway' | 'ssc' | 'banking' | 'upsc' | 'bpsc' | 'state_psc' | 'defence' | 'teaching' | 'police' | 'other';
export type JobStatus = 'active' | 'upcoming' | 'result' | 'admit_card';

export interface Job {
  id: string; title: string; titleHi: string;
  organization: string; organizationHi: string;
  category: JobCategory; totalPosts: number;
  eligibility: { education: string; educationHi: string; age: string; ageHi: string; };
  fees: { general: number; obc: number; sc_st: number; female: number; };
  importantDates: { notificationDate: string; applyStart: string; applyEnd: string; examDate: string; resultDate?: string; };
  salary: string; salaryHi: string;
  applyLink: string; notificationLink: string;
  status: JobStatus; tags: string[];
  description: string; descriptionHi: string;
  syllabus?: string; syllabusHi?: string;
  selectionProcess: string[]; selectionProcessHi: string[];
}

// Auto-generated by GitHub Actions — 2026-03-18T04:26:41.586Z
// DO NOT edit manually
export const JOBS: Job[] = [
  {
    "id": "rrb-ntpc-2025",
    "title": "RRB NTPC Recruitment 2024",
    "titleHi": "RRB एनटीपीसी भर्ती 2024",
    "organization": "Railway Recruitment Board",
    "organizationHi": "रेलवे भर्ती बोर्ड",
    "category": "railway",
    "totalPosts": 35200,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "18-30 years",
      "ageHi": "18-30 वर्ष"
    },
    "fees": {
      "general": 500,
      "obc": 500,
      "sc_st": 250,
      "female": 250
    },
    "importantDates": {
      "notificationDate": "2024-02-01",
      "applyStart": "2024-02-10",
      "applyEnd": "2024-03-31",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹19,900 - ₹92,300 per month",
    "salaryHi": "₹19,900 - ₹92,300 प्रति माह",
    "applyLink": "https://rrbapply.gov.in",
    "notificationLink": "https://rrbapply.gov.in/ntpc-notification.pdf",
    "status": "active",
    "tags": [
      "railway",
      "ntpc"
    ],
    "description": "RRB NTPC Recruitment 2024 for 35,200 posts. Apply online from 10th February 2024 to 31st March 2024.",
    "descriptionHi": "RRB एनटीपीसी भर्ती 2024 के लिए 35,200 पदों पर आवेदन करें। 10 फरवरी 2024 से 31 मार्च 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Computer Based Test",
      "Document Verification"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "ssc-cgl-2024",
    "title": "SSC CGL Recruitment 2024",
    "titleHi": "एसएससी सीजीएल भर्ती 2024",
    "organization": "Staff Selection Commission",
    "organizationHi": "स्टाफ सेलेक्शन कमीशन",
    "category": "ssc",
    "totalPosts": 6500,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "18-32 years",
      "ageHi": "18-32 वर्ष"
    },
    "fees": {
      "general": 100,
      "obc": 0,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-07-12",
      "applyStart": "2024-07-23",
      "applyEnd": "2024-08-20",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹25,500 - ₹92,300 per month",
    "salaryHi": "₹25,500 - ₹92,300 प्रति माह",
    "applyLink": "https://ssc.nic.in",
    "notificationLink": "https://ssc.nic.in/cgl-notification.pdf",
    "status": "active",
    "tags": [
      "ssc",
      "cgl"
    ],
    "description": "SSC CGL Recruitment 2024 for 6,500 posts. Apply online from 23rd July 2024 to 20th August 2024.",
    "descriptionHi": "एसएससी सीजीएल भर्ती 2024 के लिए 6,500 पदों पर आवेदन करें। 23 जुलाई 2024 से 20 अगस्त 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Computer Based Test",
      "Document Verification"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "ibps-po-2024",
    "title": "IBPS PO Recruitment 2024",
    "titleHi": "आईबीपीएस पीओ भर्ती 2024",
    "organization": "Institute of Banking Personnel Selection",
    "organizationHi": "बैंकिंग कर्मचारी चयन आयोग",
    "category": "banking",
    "totalPosts": 8575,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "20-30 years",
      "ageHi": "20-30 वर्ष"
    },
    "fees": {
      "general": 850,
      "obc": 850,
      "sc_st": 175,
      "female": 175
    },
    "importantDates": {
      "notificationDate": "2024-09-01",
      "applyStart": "2024-09-01",
      "applyEnd": "2024-09-30",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹11,765 - ₹52,170 per month",
    "salaryHi": "₹11,765 - ₹52,170 प्रति माह",
    "applyLink": "https://ibps.in",
    "notificationLink": "https://ibps.in/po-notification.pdf",
    "status": "active",
    "tags": [
      "banking",
      "po"
    ],
    "description": "IBPS PO Recruitment 2024 for 8,575 posts. Apply online from 1st September 2024 to 30th September 2024.",
    "descriptionHi": "आईबीपीएस पीओ भर्ती 2024 के लिए 8,575 पदों पर आवेदन करें। 1 सितंबर 2024 से 30 सितंबर 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Preliminary Examination",
      "Main Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "upsc-civil-services-2024",
    "title": "UPSC Civil Services Recruitment 2024",
    "titleHi": "यूपीएससी सिविल सेवा भर्ती 2024",
    "organization": "Union Public Service Commission",
    "organizationHi": "केंद्रीय सेवा आयोग",
    "category": "upsc",
    "totalPosts": 796,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "21-32 years",
      "ageHi": "21-32 वर्ष"
    },
    "fees": {
      "general": 25,
      "obc": 0,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-02-01",
      "applyStart": "2024-02-07",
      "applyEnd": "2024-03-06",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹56,100 - ₹2,25,600 per month",
    "salaryHi": "₹56,100 - ₹2,25,600 प्रति माह",
    "applyLink": "https://upsconline.nic.in",
    "notificationLink": "https://upsconline.nic.in/civil-services-notification.pdf",
    "status": "active",
    "tags": [
      "upsc",
      "civil-services"
    ],
    "description": "UPSC Civil Services Recruitment 2024 for 796 posts. Apply online from 7th February 2024 to 6th March 2024.",
    "descriptionHi": "यूपीएससी सिविल सेवा भर्ती 2024 के लिए 796 पदों पर आवेदन करें। 7 फरवरी 2024 से 6 मार्च 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Preliminary Examination",
      "Main Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "bpsc-70th-cce-2024",
    "title": "BPSC 70th CCE Recruitment 2024",
    "titleHi": "बीपीएससी 70वीं सीईई भर्ती 2024",
    "organization": "Bihar Public Service Commission",
    "organizationHi": "बिहार लोक सेवा आयोग",
    "category": "bpsc",
    "totalPosts": 562,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "20-37 years",
      "ageHi": "20-37 वर्ष"
    },
    "fees": {
      "general": 600,
      "obc": 150,
      "sc_st": 75,
      "female": 75
    },
    "importantDates": {
      "notificationDate": "2024-06-01",
      "applyStart": "2024-06-01",
      "applyEnd": "2024-07-01",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹25,500 - ₹1,22,100 per month",
    "salaryHi": "₹25,500 - ₹1,22,100 प्रति माह",
    "applyLink": "https://bpsc.bih.nic.in",
    "notificationLink": "https://bpsc.bih.nic.in/70th-cce-notification.pdf",
    "status": "active",
    "tags": [
      "bpsc",
      "70th-cce"
    ],
    "description": "BPSC 70th CCE Recruitment 2024 for 562 posts. Apply online from 1st June 2024 to 1st July 2024.",
    "descriptionHi": "बीपीएससी 70वीं सीईई भर्ती 2024 के लिए 562 पदों पर आवेदन करें। 1 जून 2024 से 1 जुलाई 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Preliminary Examination",
      "Main Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "uppsc-pcs-2024",
    "title": "UPPSC PCS Recruitment 2024",
    "titleHi": "यूपीपीएससी पीसीएस भर्ती 2024",
    "organization": "Uttar Pradesh Public Service Commission",
    "organizationHi": "उत्तर प्रदेश लोक सेवा आयोग",
    "category": "state_psc",
    "totalPosts": 364,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "21-40 years",
      "ageHi": "21-40 वर्ष"
    },
    "fees": {
      "general": 225,
      "obc": 115,
      "sc_st": 55,
      "female": 55
    },
    "importantDates": {
      "notificationDate": "2024-03-01",
      "applyStart": "2024-03-01",
      "applyEnd": "2024-04-01",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹15,600 - ₹92,300 per month",
    "salaryHi": "₹15,600 - ₹92,300 प्रति माह",
    "applyLink": "https://uppsc.gov.in",
    "notificationLink": "https://uppsc.gov.in/pcs-notification.pdf",
    "status": "active",
    "tags": [
      "state_psc",
      "pcs"
    ],
    "description": "UPPSC PCS Recruitment 2024 for 364 posts. Apply online from 1st March 2024 to 1st April 2024.",
    "descriptionHi": "यूपीपीएससी पीसीएस भर्ती 2024 के लिए 364 पदों पर आवेदन करें। 1 मार्च 2024 से 1 अप्रैल 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Preliminary Examination",
      "Main Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "bpsc-teacher-2024",
    "title": "BPSC Teacher Recruitment 2024",
    "titleHi": "बीपीएससी शिक्षक भर्ती 2024",
    "organization": "Bihar Public Service Commission",
    "organizationHi": "बिहार लोक सेवा आयोग",
    "category": "bpsc",
    "totalPosts": 15000,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "21-37 years",
      "ageHi": "21-37 वर्ष"
    },
    "fees": {
      "general": 600,
      "obc": 150,
      "sc_st": 75,
      "female": 75
    },
    "importantDates": {
      "notificationDate": "2024-08-01",
      "applyStart": "2024-08-01",
      "applyEnd": "2024-09-01",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹25,500 - ₹1,22,100 per month",
    "salaryHi": "₹25,500 - ₹1,22,100 प्रति माह",
    "applyLink": "https://bpsc.bih.nic.in",
    "notificationLink": "https://bpsc.bih.nic.in/teacher-notification.pdf",
    "status": "active",
    "tags": [
      "bpsc",
      "teacher"
    ],
    "description": "BPSC Teacher Recruitment 2024 for 15,000 posts. Apply online from 1st August 2024 to 1st September 2024.",
    "descriptionHi": "बीपीएससी शिक्षक भर्ती 2024 के लिए 15,000 पदों पर आवेदन करें। 1 अगस्त 2024 से 1 सितंबर 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Preliminary Examination",
      "Main Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "bpsc-tre-2024",
    "title": "BPSC TRE Recruitment 2024",
    "titleHi": "बीपीएससी टीआरई भर्ती 2024",
    "organization": "Bihar Public Service Commission",
    "organizationHi": "बिहार लोक सेवा आयोग",
    "category": "bpsc",
    "totalPosts": 1000,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "21-37 years",
      "ageHi": "21-37 वर्ष"
    },
    "fees": {
      "general": 600,
      "obc": 150,
      "sc_st": 75,
      "female": 75
    },
    "importantDates": {
      "notificationDate": "2024-10-01",
      "applyStart": "2024-10-01",
      "applyEnd": "2024-11-01",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹25,500 - ₹1,22,100 per month",
    "salaryHi": "₹25,500 - ₹1,22,100 प्रति माह",
    "applyLink": "https://bpsc.bih.nic.in",
    "notificationLink": "https://bpsc.bih.nic.in/tre-notification.pdf",
    "status": "active",
    "tags": [
      "bpsc",
      "tre"
    ],
    "description": "BPSC TRE Recruitment 2024 for 1,000 posts. Apply online from 1st October 2024 to 1st November 2024.",
    "descriptionHi": "बीपीएससी टीआरई भर्ती 2024 के लिए 1,000 पदों पर आवेदन करें। 1 अक्टूबर 2024 से 1 नवंबर 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Preliminary Examination",
      "Main Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "bihar-police-2024",
    "title": "Bihar Police Recruitment 2024",
    "titleHi": "बिहार पुलिस भर्ती 2024",
    "organization": "Bihar Police",
    "organizationHi": "बिहार पुलिस",
    "category": "police",
    "totalPosts": 16200,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "18-37 years",
      "ageHi": "18-37 वर्ष"
    },
    "fees": {
      "general": 150,
      "obc": 75,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-11-01",
      "applyStart": "2024-11-01",
      "applyEnd": "2024-12-01",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹21,700 - ₹69,100 per month",
    "salaryHi": "₹21,700 - ₹69,100 प्रति माह",
    "applyLink": "https://csbc.bih.nic.in",
    "notificationLink": "https://csbc.bih.nic.in/police-notification.pdf",
    "status": "active",
    "tags": [
      "police",
      "bihar-police"
    ],
    "description": "Bihar Police Recruitment 2024 for 16,200 posts. Apply online from 1st November 2024 to 1st December 2024.",
    "descriptionHi": "बिहार पुलिस भर्ती 2024 के लिए 16,200 पदों पर आवेदन करें। 1 नवंबर 2024 से 1 दिसंबर 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Physical Efficiency Test",
      "Written Examination",
      "Document Verification"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "up-police-2024",
    "title": "UP Police Recruitment 2024",
    "titleHi": "यूपी पुलिस भर्ती 2024",
    "organization": "Uttar Pradesh Police",
    "organizationHi": "उत्तर प्रदेश पुलिस",
    "category": "police",
    "totalPosts": 25000,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "18-28 years",
      "ageHi": "18-28 वर्ष"
    },
    "fees": {
      "general": 400,
      "obc": 200,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-12-01",
      "applyStart": "2024-12-01",
      "applyEnd": "2025-01-01",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹21,700 - ₹69,100 per month",
    "salaryHi": "₹21,700 - ₹69,100 प्रति माह",
    "applyLink": "https://uppbpb.gov.in",
    "notificationLink": "https://uppbpb.gov.in/police-notification.pdf",
    "status": "active",
    "tags": [
      "police",
      "up-police"
    ],
    "description": "UP Police Recruitment 2024 for 25,000 posts. Apply online from 1st December 2024 to 1st January 2025.",
    "descriptionHi": "यूपी पुलिस भर्ती 2024 के लिए 25,000 पदों पर आवेदन करें। 1 दिसंबर 2024 से 1 जनवरी 2025 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Physical Efficiency Test",
      "Written Examination",
      "Document Verification"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "drdo-2024",
    "title": "DRDO Recruitment 2024",
    "titleHi": "डीआरडीओ भर्ती 2024",
    "organization": "Defence Research and Development Organisation",
    "organizationHi": "रक्षा अनुसंधान और विकास संगठन",
    "category": "other",
    "totalPosts": 500,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "18-28 years",
      "ageHi": "18-28 वर्ष"
    },
    "fees": {
      "general": 0,
      "obc": 0,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-06-01",
      "applyStart": "2024-06-01",
      "applyEnd": "2024-07-01",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹25,500 - ₹1,22,100 per month",
    "salaryHi": "₹25,500 - ₹1,22,100 प्रति माह",
    "applyLink": "https://drdo.gov.in",
    "notificationLink": "https://drdo.gov.in/recruitment-notification.pdf",
    "status": "active",
    "tags": [
      "other",
      "drdo"
    ],
    "description": "DRDO Recruitment 2024 for 500 posts. Apply online from 1st June 2024 to 1st July 2024.",
    "descriptionHi": "डीआरडीओ भर्ती 2024 के लिए 500 पदों पर आवेदन करें। 1 जून 2024 से 1 जुलाई 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Written Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "isro-2024",
    "title": "ISRO Recruitment 2024",
    "titleHi": "आईएसआरओ भर्ती 2024",
    "organization": "Indian Space Research Organisation",
    "organizationHi": "भारतीय अंतरिक्ष अनुसंधान संगठन",
    "category": "other",
    "totalPosts": 150,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "18-28 years",
      "ageHi": "18-28 वर्ष"
    },
    "fees": {
      "general": 0,
      "obc": 0,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-08-01",
      "applyStart": "2024-08-01",
      "applyEnd": "2024-09-01",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹25,500 - ₹1,22,100 per month",
    "salaryHi": "₹25,500 - ₹1,22,100 प्रति माह",
    "applyLink": "https://isro.gov.in",
    "notificationLink": "https://isro.gov.in/recruitment-notification.pdf",
    "status": "active",
    "tags": [
      "other",
      "isro"
    ],
    "description": "ISRO Recruitment 2024 for 150 posts. Apply online from 1st August 2024 to 1st September 2024.",
    "descriptionHi": "आईएसआरओ भर्ती 2024 के लिए 150 पदों पर आवेदन करें। 1 अगस्त 2024 से 1 सितंबर 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Written Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "ctet-2024",
    "title": "CTET Recruitment 2024",
    "titleHi": "सीटीईटी भर्ती 2024",
    "organization": "Central Board of Secondary Education",
    "organizationHi": "केंद्रीय माध्यमिक शिक्षा बोर्ड",
    "category": "teaching",
    "totalPosts": 20000,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "18-30 years",
      "ageHi": "18-30 वर्ष"
    },
    "fees": {
      "general": 1000,
      "obc": 500,
      "sc_st": 250,
      "female": 250
    },
    "importantDates": {
      "notificationDate": "2024-09-01",
      "applyStart": "2024-09-01",
      "applyEnd": "2024-10-01",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹30,000 - ₹1,20,000 per month",
    "salaryHi": "₹30,000 - ₹1,20,000 प्रति माह",
    "applyLink": "https://cbse.gov.in",
    "notificationLink": "https://cbse.gov.in/ctet-notification.pdf",
    "status": "active",
    "tags": [
      "teaching",
      "ctet"
    ],
    "description": "CTET Recruitment 2024 for 20,000 posts. Apply online from 1st September 2024 to 1st October 2024.",
    "descriptionHi": "सीटीईटी भर्ती 2024 के लिए 20,000 पदों पर आवेदन करें। 1 सितंबर 2024 से 1 अक्टूबर 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Written Examination"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "dsssb-2024",
    "title": "DSSSB Recruitment 2024",
    "titleHi": "डीएसएसएसबी भर्ती 2024",
    "organization": "Delhi Subordinate Services Selection Board",
    "organizationHi": "दिल्ली अधीनस्थ सेवा चयन बोर्ड",
    "category": "teaching",
    "totalPosts": 10000,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "18-30 years",
      "ageHi": "18-30 वर्ष"
    },
    "fees": {
      "general": 100,
      "obc": 0,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-10-01",
      "applyStart": "2024-10-01",
      "applyEnd": "2024-11-01",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹25,500 - ₹1,22,100 per month",
    "salaryHi": "₹25,500 - ₹1,22,100 प्रति माह",
    "applyLink": "https://dsssb.delhigovt.nic.in",
    "notificationLink": "https://dsssb.delhigovt.nic.in/recruitment-notification.pdf",
    "status": "active",
    "tags": [
      "teaching",
      "dsssb"
    ],
    "description": "DSSSB Recruitment 2024 for 10,000 posts. Apply online from 1st October 2024 to 1st November 2024.",
    "descriptionHi": "डीएसएसएसबी भर्ती 2024 के लिए 10,000 पदों पर आवेदन करें। 1 अक्टूबर 2024 से 1 नवंबर 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Written Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "kvs-2024",
    "title": "KVS Recruitment 2024",
    "titleHi": "केवीएस भर्ती 2024",
    "organization": "Kendriya Vidyalaya Sangathan",
    "organizationHi": "केंद्रीय विद्यालय संगठन",
    "category": "teaching",
    "totalPosts": 5000,
    "eligibility": {
      "education": "Graduation",
      "educationHi": "ग्रेजुएशन",
      "age": "18-30 years",
      "ageHi": "18-30 वर्ष"
    },
    "fees": {
      "general": 0,
      "obc": 0,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-11-01",
      "applyStart": "2024-11-01",
      "applyEnd": "2024-12-01",
      "examDate": "2025-12-01",
      "resultDate": ""
    },
    "salary": "₹25,500 - ₹1,22,100 per month",
    "salaryHi": "₹25,500 - ₹1,22,100 प्रति माह",
    "applyLink": "https://kvsangathan.nic.in",
    "notificationLink": "https://kvsangathan.nic.in/recruitment-notification.pdf",
    "status": "active",
    "tags": [
      "teaching",
      "kvs"
    ],
    "description": "KVS Recruitment 2024 for 5,000 posts. Apply online from 1st November 2024 to 1st December 2024.",
    "descriptionHi": "केवीएस भर्ती 2024 के लिए 5,000 पदों पर आवेदन करें। 1 नवंबर 2024 से 1 दिसंबर 2024 तक ऑनलाइन आवेदन करें।",
    "selectionProcess": [
      "Written Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  }
];

export const CATEGORIES = [
  { id: 'all', label: 'All Jobs', labelHi: 'सभी नौकरियां', icon: '🏛️' },
  { id: 'railway', label: 'Railway', labelHi: 'रेलवे', icon: '🚂' },
  { id: 'ssc', label: 'SSC', labelHi: 'एसएससी', icon: '📋' },
  { id: 'banking', label: 'Banking', labelHi: 'बैंकिंग', icon: '🏦' },
  { id: 'upsc', label: 'UPSC', labelHi: 'यूपीएससी', icon: '⭐' },
  { id: 'bpsc', label: 'BPSC', labelHi: 'बीपीएससी', icon: '🎯' },
  { id: 'state_psc', label: 'State PSC', labelHi: 'राज्य पीएससी', icon: '🗺️' },
  { id: 'defence', label: 'Defence', labelHi: 'रक्षा', icon: '🪖' },
  { id: 'teaching', label: 'Teaching', labelHi: 'शिक्षण', icon: '📚' },
  { id: 'police', label: 'Police', labelHi: 'पुलिस', icon: '👮' },
  { id: 'other', label: 'Other', labelHi: 'अन्य', icon: '🏢' },
];

export const STATUS_CONFIG = {
  active: { label: 'Apply Now', labelHi: 'अभी आवेदन करें', color: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200' },
  upcoming: { label: 'Upcoming', labelHi: 'आने वाला', color: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200' },
  result: { label: 'Result Out', labelHi: 'परिणाम आया', color: 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200' },
  admit_card: { label: 'Admit Card', labelHi: 'एडमिट कार्ड', color: 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200' },
};
