export type JobCategory = 'railway' | 'ssc' | 'banking' | 'upsc' | 'bpsc' | 'state_psc' | 'defence' | 'teaching' | 'police' | 'other';
export type JobStatus = 'active' | 'upcoming' | 'result' | 'admit_card';

export interface Job {
  id: string; title: string; titleHi: string;
  organization: string; organizationHi: string;
  category: JobCategory; totalPosts: number;
  eligibility: { education: string; educationHi: string; age: string; ageHi: string; };
  fees: { general: number; obc: number; sc_st: number; female: number; };
  importantDates: { notificationDate: string; applyStart: string; applyEnd: string; examDate: string; resultDate?: string; };
  salary: string; salaryHi: string;
  applyLink: string; notificationLink: string;
  status: JobStatus; tags: string[];
  description: string; descriptionHi: string;
  syllabus?: string; syllabusHi?: string;
  selectionProcess: string[]; selectionProcessHi: string[];
}

// Auto-generated by GitHub Actions — 2026-03-18T21:03:48.089Z
// DO NOT edit manually
export const JOBS: Job[] = [
  {
    "id": "rrb-ntpc-2024",
    "title": "RRB NTPC Recruitment 2024",
    "titleHi": "RRB एनटीपीसी भर्ती 2024",
    "organization": "Railway Recruitment Board",
    "organizationHi": "रेलवे भर्ती बोर्ड",
    "category": "railway",
    "totalPosts": 35281,
    "eligibility": {
      "education": "Bachelor’s degree",
      "educationHi": "बैचलर’स डिग्री",
      "age": "18-30 years",
      "ageHi": "18-30 वर्ष"
    },
    "fees": {
      "general": 500,
      "obc": 500,
      "sc_st": 250,
      "female": 250
    },
    "importantDates": {
      "notificationDate": "2024-03-30",
      "applyStart": "2024-04-01",
      "applyEnd": "2024-04-30",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹19,900 - ₹63,200 per month",
    "salaryHi": "₹19,900 - ₹63,200 प्रति माह",
    "applyLink": "https://rrbapply.gov.in",
    "notificationLink": "https://rrbapply.gov.in/ntpc-2024-notification.pdf",
    "status": "active",
    "tags": [
      "railway",
      "ntpc"
    ],
    "description": "Recruitment for 35281 Non-Technical Popular Categories (NTPC) posts in Indian Railways.",
    "descriptionHi": "भारतीय रेलवे में 35281 नॉन-टेक्निकल पॉपुलर कैटेगरी (एनटीपीसी) पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Computer-Based Test",
      "Document Verification"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "ssc-cgl-2024",
    "title": "SSC CGL Recruitment 2024",
    "titleHi": "एसएससी सीजीएल भर्ती 2024",
    "organization": "Staff Selection Commission",
    "organizationHi": "स्टाफ सेलेक्शन कमीशन",
    "category": "ssc",
    "totalPosts": 7035,
    "eligibility": {
      "education": "Bachelor’s degree",
      "educationHi": "बैचलर’स डिग्री",
      "age": "18-32 years",
      "ageHi": "18-32 वर्ष"
    },
    "fees": {
      "general": 100,
      "obc": 0,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-02-07",
      "applyStart": "2024-02-07",
      "applyEnd": "2024-03-06",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹25,500 - ₹92,300 per month",
    "salaryHi": "₹25,500 - ₹92,300 प्रति माह",
    "applyLink": "https://ssc.nic.in",
    "notificationLink": "https://ssc.nic.in/cgl-2024-notification.pdf",
    "status": "active",
    "tags": [
      "ssc",
      "cgl"
    ],
    "description": "Recruitment for 7035 Combined Graduate Level (CGL) posts in various government departments.",
    "descriptionHi": "विभिन्न सरकारी विभागों में 7035 संयुक्त स्नातक स्तर (सीजीएल) पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Computer-Based Test",
      "Descriptive Test",
      "Document Verification"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "ibps-po-2024",
    "title": "IBPS PO Recruitment 2024",
    "titleHi": "आईबीपीएस पीओ भर्ती 2024",
    "organization": "Institute of Banking Personnel Selection",
    "organizationHi": "बैंकिंग कर्मचारी चयन बोर्ड",
    "category": "banking",
    "totalPosts": 8572,
    "eligibility": {
      "education": "Bachelor’s degree",
      "educationHi": "बैचलर’स डिग्री",
      "age": "20-30 years",
      "ageHi": "20-30 वर्ष"
    },
    "fees": {
      "general": 850,
      "obc": 850,
      "sc_st": 175,
      "female": 175
    },
    "importantDates": {
      "notificationDate": "2024-06-01",
      "applyStart": "2024-06-01",
      "applyEnd": "2024-06-21",
      "examDate": "2025-09-01",
      "resultDate": ""
    },
    "salary": "₹41,000 - ₹1,23,000 per month",
    "salaryHi": "₹41,000 - ₹1,23,000 प्रति माह",
    "applyLink": "https://ibps.in",
    "notificationLink": "https://ibps.in/po-2024-notification.pdf",
    "status": "active",
    "tags": [
      "banking",
      "po"
    ],
    "description": "Recruitment for 8572 Probationary Officers (PO) posts in various banks.",
    "descriptionHi": "विभिन्न बैंकों में 8572 प्रोबेशनरी ऑफिसर (पीओ) पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Preliminary Examination",
      "Main Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "upsc-cds-2024",
    "title": "UPSC CDS Recruitment 2024",
    "titleHi": "यूपीएससी सीडीएस भर्ती 2024",
    "organization": "Union Public Service Commission",
    "organizationHi": "संघ लोक सेवा आयोग",
    "category": "upsc",
    "totalPosts": 341,
    "eligibility": {
      "education": "Bachelor’s degree",
      "educationHi": "बैचलर’स डिग्री",
      "age": "18-24 years",
      "ageHi": "18-24 वर्ष"
    },
    "fees": {
      "general": 200,
      "obc": 0,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-09-02",
      "applyStart": "2024-09-02",
      "applyEnd": "2024-09-22",
      "examDate": "2025-02-01",
      "resultDate": ""
    },
    "salary": "₹56,100 - ₹1,77,500 per month",
    "salaryHi": "₹56,100 - ₹1,77,500 प्रति माह",
    "applyLink": "https://upsc.gov.in",
    "notificationLink": "https://upsc.gov.in/cds-2024-notification.pdf",
    "status": "active",
    "tags": [
      "upsc",
      "cds"
    ],
    "description": "Recruitment for 341 Combined Defence Services (CDS) posts in Indian Defence Forces.",
    "descriptionHi": "भारतीय रक्षा बलों में 341 संयुक्त रक्षा सेवा (सीडीएस) पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Written Examination",
      "SSB Interview",
      "Medical Test"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "bpsc-70th-cce-2024",
    "title": "BPSC 70th CCE Recruitment 2024",
    "titleHi": "बीपीएससी 70वीं सीईई भर्ती 2024",
    "organization": "Bihar Public Service Commission",
    "organizationHi": "बिहार लोक सेवा आयोग",
    "category": "bpsc",
    "totalPosts": 562,
    "eligibility": {
      "education": "Bachelor’s degree",
      "educationHi": "बैचलर’स डिग्री",
      "age": "20-37 years",
      "ageHi": "20-37 वर्ष"
    },
    "fees": {
      "general": 600,
      "obc": 600,
      "sc_st": 150,
      "female": 150
    },
    "importantDates": {
      "notificationDate": "2024-01-10",
      "applyStart": "2024-01-10",
      "applyEnd": "2024-02-09",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹25,500 - ₹92,300 per month",
    "salaryHi": "₹25,500 - ₹92,300 प्रति माह",
    "applyLink": "https://bpsc.bih.nic.in",
    "notificationLink": "https://bpsc.bih.nic.in/70th-cce-2024-notification.pdf",
    "status": "active",
    "tags": [
      "bpsc",
      "70th-cce"
    ],
    "description": "Recruitment for 562 Combined Competitive Examination (CCE) posts in Bihar Government.",
    "descriptionHi": "बिहार सरकार में 562 संयुक्त प्रतियोगी परीक्षा (सीईई) पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Preliminary Examination",
      "Main Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "uppsc-pcs-2024",
    "title": "UPPSC PCS Recruitment 2024",
    "titleHi": "यूपीपीएससी पीसीएस भर्ती 2024",
    "organization": "Uttar Pradesh Public Service Commission",
    "organizationHi": "उत्तर प्रदेश लोक सेवा आयोग",
    "category": "state_psc",
    "totalPosts": 380,
    "eligibility": {
      "education": "Bachelor’s degree",
      "educationHi": "बैचलर’स डिग्री",
      "age": "21-40 years",
      "ageHi": "21-40 वर्ष"
    },
    "fees": {
      "general": 225,
      "obc": 225,
      "sc_st": 115,
      "female": 115
    },
    "importantDates": {
      "notificationDate": "2024-02-20",
      "applyStart": "2024-02-20",
      "applyEnd": "2024-03-20",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹15,600 - ₹39,100 per month",
    "salaryHi": "₹15,600 - ₹39,100 प्रति माह",
    "applyLink": "https://uppsc.up.nic.in",
    "notificationLink": "https://uppsc.up.nic.in/pcs-2024-notification.pdf",
    "status": "active",
    "tags": [
      "state_psc",
      "pcs"
    ],
    "description": "Recruitment for 380 Provincial Civil Service (PCS) posts in Uttar Pradesh Government.",
    "descriptionHi": "उत्तर प्रदेश सरकार में 380 प्रांतीय सिविल सेवा (पीसीएस) पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Preliminary Examination",
      "Main Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "mppsc-2024",
    "title": "MPPSC Recruitment 2024",
    "titleHi": "एमपीपीएससी भर्ती 2024",
    "organization": "Madhya Pradesh Public Service Commission",
    "organizationHi": "मध्य प्रदेश लोक सेवा आयोग",
    "category": "state_psc",
    "totalPosts": 271,
    "eligibility": {
      "education": "Bachelor’s degree",
      "educationHi": "बैचलर’स डिग्री",
      "age": "18-40 years",
      "ageHi": "18-40 वर्ष"
    },
    "fees": {
      "general": 500,
      "obc": 500,
      "sc_st": 250,
      "female": 250
    },
    "importantDates": {
      "notificationDate": "2024-03-01",
      "applyStart": "2024-03-01",
      "applyEnd": "2024-04-01",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹15,600 - ₹39,100 per month",
    "salaryHi": "₹15,600 - ₹39,100 प्रति माह",
    "applyLink": "https://mppsc.mp.gov.in",
    "notificationLink": "https://mppsc.mp.gov.in/2024-notification.pdf",
    "status": "active",
    "tags": [
      "state_psc"
    ],
    "description": "Recruitment for 271 various posts in Madhya Pradesh Government.",
    "descriptionHi": "मध्य प्रदेश सरकार में विभिन्न पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Preliminary Examination",
      "Main Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "rpf-2024",
    "title": "RPF Recruitment 2024",
    "titleHi": "आरपीएफ भर्ती 2024",
    "organization": "Railway Protection Force",
    "organizationHi": "रेलवे प्रोटेक्शन फोर्स",
    "category": "railway",
    "totalPosts": 7989,
    "eligibility": {
      "education": "10th pass",
      "educationHi": "10वीं पास",
      "age": "18-25 years",
      "ageHi": "18-25 वर्ष"
    },
    "fees": {
      "general": 500,
      "obc": 500,
      "sc_st": 250,
      "female": 250
    },
    "importantDates": {
      "notificationDate": "2024-04-01",
      "applyStart": "2024-04-01",
      "applyEnd": "2024-05-01",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹21,700 - ₹69,100 per month",
    "salaryHi": "₹21,700 - ₹69,100 प्रति माह",
    "applyLink": "https://rpf.indianrailways.gov.in",
    "notificationLink": "https://rpf.indianrailways.gov.in/2024-notification.pdf",
    "status": "active",
    "tags": [
      "railway",
      "rpf"
    ],
    "description": "Recruitment for 7989 Constable posts in Railway Protection Force.",
    "descriptionHi": "रेलवे प्रोटेक्शन फोर्स में 7989 कांस्टेबल पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Computer-Based Test",
      "Physical Efficiency Test",
      "Document Verification"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "bihar-stet-2024",
    "title": "Bihar STET Recruitment 2024",
    "titleHi": "बिहार एसटीईटी भर्ती 2024",
    "organization": "Bihar School Examination Board",
    "organizationHi": "बिहार विद्यालय परीक्षा समिति",
    "category": "teaching",
    "totalPosts": 10000,
    "eligibility": {
      "education": "Bachelor’s degree",
      "educationHi": "बैचलर’स डिग्री",
      "age": "21-40 years",
      "ageHi": "21-40 वर्ष"
    },
    "fees": {
      "general": 500,
      "obc": 500,
      "sc_st": 250,
      "female": 250
    },
    "importantDates": {
      "notificationDate": "2024-02-20",
      "applyStart": "2024-02-20",
      "applyEnd": "2024-03-20",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹25,500 - ₹92,300 per month",
    "salaryHi": "₹25,500 - ₹92,300 प्रति माह",
    "applyLink": "https://biharboardonline.com",
    "notificationLink": "https://biharboardonline.com/stet-2024-notification.pdf",
    "status": "active",
    "tags": [
      "teaching",
      "stet"
    ],
    "description": "Recruitment for 10000 Teacher posts in Bihar Government.",
    "descriptionHi": "बिहार सरकार में 10000 शिक्षक पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Written Examination",
      "Document Verification"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "delhi-police-2024",
    "title": "Delhi Police Recruitment 2024",
    "titleHi": "दिल्ली पुलिस भर्ती 2024",
    "organization": "Delhi Police",
    "organizationHi": "दिल्ली पुलिस",
    "category": "police",
    "totalPosts": 5062,
    "eligibility": {
      "education": "10th pass",
      "educationHi": "10वीं पास",
      "age": "18-25 years",
      "ageHi": "18-25 वर्ष"
    },
    "fees": {
      "general": 100,
      "obc": 0,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-03-01",
      "applyStart": "2024-03-01",
      "applyEnd": "2024-04-01",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹21,700 - ₹69,100 per month",
    "salaryHi": "₹21,700 - ₹69,100 प्रति माह",
    "applyLink": "https://delhipolice.nic.in",
    "notificationLink": "https://delhipolice.nic.in/2024-notification.pdf",
    "status": "active",
    "tags": [
      "police"
    ],
    "description": "Recruitment for 5062 Constable posts in Delhi Police.",
    "descriptionHi": "दिल्ली पुलिस में 5062 कांस्टेबल पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Computer-Based Test",
      "Physical Efficiency Test",
      "Document Verification"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "up-police-2024",
    "title": "UP Police Recruitment 2024",
    "titleHi": "यूपी पुलिस भर्ती 2024",
    "organization": "Uttar Pradesh Police",
    "organizationHi": "उत्तर प्रदेश पुलिस",
    "category": "police",
    "totalPosts": 52173,
    "eligibility": {
      "education": "10th pass",
      "educationHi": "10वीं पास",
      "age": "18-28 years",
      "ageHi": "18-28 वर्ष"
    },
    "fees": {
      "general": 400,
      "obc": 400,
      "sc_st": 200,
      "female": 200
    },
    "importantDates": {
      "notificationDate": "2024-02-20",
      "applyStart": "2024-02-20",
      "applyEnd": "2024-03-20",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹21,700 - ₹69,100 per month",
    "salaryHi": "₹21,700 - ₹69,100 प्रति माह",
    "applyLink": "https://uppolice.gov.in",
    "notificationLink": "https://uppolice.gov.in/2024-notification.pdf",
    "status": "active",
    "tags": [
      "police"
    ],
    "description": "Recruitment for 52173 Constable posts in Uttar Pradesh Police.",
    "descriptionHi": "उत्तर प्रदेश पुलिस में 52173 कांस्टेबल पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Computer-Based Test",
      "Physical Efficiency Test",
      "Document Verification"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "bihar-police-2024",
    "title": "Bihar Police Recruitment 2024",
    "titleHi": "बिहार पुलिस भर्ती 2024",
    "organization": "Bihar Police",
    "organizationHi": "बिहार पुलिस",
    "category": "police",
    "totalPosts": 16200,
    "eligibility": {
      "education": "10th pass",
      "educationHi": "10वीं पास",
      "age": "18-25 years",
      "ageHi": "18-25 वर्ष"
    },
    "fees": {
      "general": 400,
      "obc": 400,
      "sc_st": 200,
      "female": 200
    },
    "importantDates": {
      "notificationDate": "2024-01-10",
      "applyStart": "2024-01-10",
      "applyEnd": "2024-02-09",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹21,700 - ₹69,100 per month",
    "salaryHi": "₹21,700 - ₹69,100 प्रति माह",
    "applyLink": "https://bihapolice.bih.nic.in",
    "notificationLink": "https://bihapolice.bih.nic.in/2024-notification.pdf",
    "status": "active",
    "tags": [
      "police"
    ],
    "description": "Recruitment for 16200 Constable posts in Bihar Police.",
    "descriptionHi": "बिहार पुलिस में 16200 कांस्टेबल पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Computer-Based Test",
      "Physical Efficiency Test",
      "Document Verification"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "drdo-2024",
    "title": "DRDO Recruitment 2024",
    "titleHi": "डीआरडीओ भर्ती 2024",
    "organization": "Defence Research and Development Organisation",
    "organizationHi": "रक्षा अनुसंधान और विकास संगठन",
    "category": "other",
    "totalPosts": 154,
    "eligibility": {
      "education": "Bachelor’s degree",
      "educationHi": "बैचलर’स डिग्री",
      "age": "18-28 years",
      "ageHi": "18-28 वर्ष"
    },
    "fees": {
      "general": 0,
      "obc": 0,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-03-01",
      "applyStart": "2024-03-01",
      "applyEnd": "2024-04-01",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹56,100 - ₹1,77,500 per month",
    "salaryHi": "₹56,100 - ₹1,77,500 प्रति माह",
    "applyLink": "https://drdo.gov.in",
    "notificationLink": "https://drdo.gov.in/2024-notification.pdf",
    "status": "active",
    "tags": [
      "other",
      "drdo"
    ],
    "description": "Recruitment for 154 Scientist posts in Defence Research and Development Organisation.",
    "descriptionHi": "रक्षा अनुसंधान और विकास संगठन में 154 वैज्ञानिक पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Written Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  },
  {
    "id": "isro-2024",
    "title": "ISRO Recruitment 2024",
    "titleHi": "आईएसआरओ भर्ती 2024",
    "organization": "Indian Space Research Organisation",
    "organizationHi": "भारतीय अंतरिक्ष अनुसंधान संगठन",
    "category": "other",
    "totalPosts": 182,
    "eligibility": {
      "education": "Bachelor’s degree",
      "educationHi": "बैचलर’स डिग्री",
      "age": "18-35 years",
      "ageHi": "18-35 वर्ष"
    },
    "fees": {
      "general": 0,
      "obc": 0,
      "sc_st": 0,
      "female": 0
    },
    "importantDates": {
      "notificationDate": "2024-02-20",
      "applyStart": "2024-02-20",
      "applyEnd": "2024-03-20",
      "examDate": "2025-06-01",
      "resultDate": ""
    },
    "salary": "₹56,100 - ₹1,77,500 per month",
    "salaryHi": "₹56,100 - ₹1,77,500 प्रति माह",
    "applyLink": "https://isro.gov.in",
    "notificationLink": "https://isro.gov.in/2024-notification.pdf",
    "status": "active",
    "tags": [
      "other",
      "isro"
    ],
    "description": "Recruitment for 182 Scientist posts in Indian Space Research Organisation.",
    "descriptionHi": "भारतीय अंतरिक्ष अनुसंधान संगठन में 182 वैज्ञानिक पदों के लिए भर्ती ।",
    "selectionProcess": [
      "Written Examination",
      "Interview"
    ],
    "selectionProcessHi": []
  }
];

export const CATEGORIES = [
  { id: 'all', label: 'All Jobs', labelHi: 'सभी नौकरियां', icon: '🏛️' },
  { id: 'railway', label: 'Railway', labelHi: 'रेलवे', icon: '🚂' },
  { id: 'ssc', label: 'SSC', labelHi: 'एसएससी', icon: '📋' },
  { id: 'banking', label: 'Banking', labelHi: 'बैंकिंग', icon: '🏦' },
  { id: 'upsc', label: 'UPSC', labelHi: 'यूपीएससी', icon: '⭐' },
  { id: 'bpsc', label: 'BPSC', labelHi: 'बीपीएससी', icon: '🎯' },
  { id: 'state_psc', label: 'State PSC', labelHi: 'राज्य पीएससी', icon: '🗺️' },
  { id: 'defence', label: 'Defence', labelHi: 'रक्षा', icon: '🪖' },
  { id: 'teaching', label: 'Teaching', labelHi: 'शिक्षण', icon: '📚' },
  { id: 'police', label: 'Police', labelHi: 'पुलिस', icon: '👮' },
  { id: 'other', label: 'Other', labelHi: 'अन्य', icon: '🏢' },
];

export const STATUS_CONFIG = {
  active: { label: 'Apply Now', labelHi: 'अभी आवेदन करें', color: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200' },
  upcoming: { label: 'Upcoming', labelHi: 'आने वाला', color: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200' },
  result: { label: 'Result Out', labelHi: 'परिणाम आया', color: 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200' },
  admit_card: { label: 'Admit Card', labelHi: 'एडमिट कार्ड', color: 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200' },
};
